<?php

namespace Database\Seeders;

use App\Models\Profession;
use Illuminate\Database\Seeder;

class ProfessionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Profession::insert([
            ['name' => 'Akolita', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Banita', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Berserker z Norski', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chłop', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ciura obozowa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cyrkowiec', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cyrulik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fanatyk', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flisak', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Giermek', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gladiator', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Goniec', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Górnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Guślarz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hiena cmentarna', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kanciarz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kozak kiselvski', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Leśnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Łowca', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Łowca nagród', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mieszczanin', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mytnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Najemnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ochotnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ochroniarz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Oprych', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Paź', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Podżegacz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Porywacz zwłok', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Posłaniec', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Przemytnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Przepatrywacz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Przewoźnk', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rybak', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rzecznik rodu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rzemieślnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rzezimieszek', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Skryba', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sługa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Strażnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Strażnik dróg', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Strażnik pól', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Strażnik więzienny', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Szczurołap', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Szermierz estalijski', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Szlachcic', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Śmieciarz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tarczownik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uczeń czarodzieja', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Węglarz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Włoczykij', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wojownik klanowy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Woźnica', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zabójca trolli', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zarządca', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Złodziej', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Żak', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Żeglarz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Żołnierz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Żołnierz okrętowy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Arcykapłan', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Arcymag', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Arystokrata', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bard', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Biczownik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bosman', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Demagog', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dworzanin', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fechmistrz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Herold', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Herszt banitów', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Inzynier', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kapitan', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kapłan', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Karczmarz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Książe złodziei', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kupiec', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Leśny duch', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Łowca czarownic', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Łowca wampirów', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majordomus', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Medyk', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mistrz cieni', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mistrz gildii', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mistrz magii', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mistrz rzemiosła', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mistrz zakonny', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nawigator', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Odkrywca', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Oficer', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Oprawca', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Paser', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rajtar', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Reketer', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rozbójnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rycerz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sierżant', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Skrytobójca', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Strzelec', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Szampierz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Szarlatan', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Szpieg', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uczony', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Urzędnik', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Weteran', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wędrowny czarodziej', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Włamywacz', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wybraniec boży', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zabójca demonów', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zabójca olbrzmów', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zwadźca', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zwiadowca', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
