<?php

namespace Database\Seeders;

use App\Models\Profession;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProfessionCharacteristicsSeeder extends Seeder
{
    private array  $characteristicMap = [
        'ww' => 1,
        'us' => 2,
        'k' => 3,
        'odp' => 4,
        'zr' => 5,
        'int' => 6,
        'sw' => 7,
        'ogd' => 8,
        'a' => 9,
        'zyw' => 10,
        'sz' => 13,
        'mag' => 14,
    ];
    private array $professionsData = [
        'Akolita' => [
            'ww' => 5,
            'us' => 5,
            'odp' => 5,
            'int' => 10,
            'sw' => 10,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Banita' => [
            'ww' => 10,
            'us' => 10,
            'zr' => 10,
            'int' => 5,
            'a' => 1,
            'zyw' => 2,
        ],
        'Berseker z Norski' => [
            'ww' => 15,
            'k' => 10,
            'odp' => 10,
            'sw' => 10,
            'zyw' => 2,
        ],
        'Chłop' => [
            'ww' => 5,
            'us' => 5,
            'k' => 5,
            'odp' => 10,
            'zr' => 5,
            'sw' => 5,
            'zyw' => 2,
        ],
        'Ciura obozowa' => [
            'odp' => 5,
            'zr' => 10,
            'int' => 5,
            'sw' => 5,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Cyrkowiec' => [
            'ww' => 5,
            'us' => 10,
            'zr' => 10,
            'sw' => 5,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Cyrulik' => [
            'ww' => 5,
            'zr' => 10,
            'int' => 10,
            'sw' => 10,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Fanatyk' => [
            'ww' => 10,
            'k' => 5,
            'odp' => 10,
            'sw' => 10,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Flisak' => [
            'ww' => 10,
            'us' => 5,
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 5,
            'zyw' => 2,
        ],
        'Giermek' => [
            'ww' => 10,
            'us' => 5,
            'k' => 5,
            'odp' => 5,
            'zr' => 5,
            'ogd' => 5,
            'a' => 1,
            'zyw' => 2,
        ],
        'Gladiator' => [
            'ww' => 15,
            'odp' => 10,
            'zr' => 10,
            'sw' => 10,
            'zyw' => 2,
        ],
        'Goniec' => [
            'ww' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 5,
            'sw' => 5,
            'zyw' => 2,
            'sz' => 1,
        ],
        'Górnik' => [
            'ww' => 5,
            'us' => 5,
            'k' => 10,
            'odp' => 5,
            'sw' => 5,
            'zyw' => 2,
        ],
        'Guślarz' => [
            'odp' => 5,
            'zr' => 5,
            'int' => 5,
            'sw' => 10,
            'ogd' => 10,
            'zyw' => 2,
            'mag' => 1,
        ],
        'Hiena cmentarna' => [
            'ww' => 10,
            'zr' => 10,
            'int' => 10,
            'sw' => 10,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Kanciarz' => [
            'ww' => 5,
            'us' => 5,
            'zr' => 10,
            'int' => 5,
            'sw' => 5,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Kozak kislevski' => [
            'ww' => 10,
            'us' => 10,
            'odp' => 10,
            'sw' => 10,
            'zyw' => 2,
        ],
        'Leśnik' => [
            'ww' => 10,
            'k' => 10,
            'zr' => 5,
            'sw' => 10,
            'zyw' => 3,
        ],
        'Łowca' => [
            'us' => 15,
            'odp' => 5,
            'zr' => 10,
            'int' => 5,
            'zyw' => 3,
        ],
        'Łowca nagród' => [
            'ww' => 5,
            'us' => 10,
            'k' => 5,
            'zr' => 10,
            'zyw' => 2,
        ],
        'Mieszczanin' => [
            'ww' => 5,
            'zr' => 5,
            'int' => 10,
            'sw' => 5,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Mytnik' => [
            'ww' => 10,
            'us' => 5,
            'k' => 5,
            'odp' => 10,
            'zr' => 5,
            'sw' => 5,
            'zyw' => 2,
        ],
        'Najemnik' => [
            'ww' => 10,
            'us' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 5,
            'sw' => 5,
            'a' => 1,
            'zyw' => 2,
        ],
        'Ochotnik' => [
            'ww' => 10,
            'us' => 5,
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'zyw' => 2,
        ],
        'Ochroniarz' => [
            'ww' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 5,
            'a' => 1,
            'zyw' => 3,
        ],
        'Oprych' => [
            'ww' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 5,
            'sw' => 5,
            'ogd' => 5,
            'a' => 1,
            'zyw' => 2,
        ],
        'Paź' => [
            'zr' => 10,
            'int' => 10,
            'sw' => 5,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Podżegacz' => [
            'ww' => 5,
            'us' => 5,
            'zr' => 5,
            'int' => 10,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Porywacz zwłok' => [
            'ww' => 5,
            'us' => 5,
            'k' => 5,
            'zr' => 10,
            'sw' => 10,
            'zyw' => 2,
        ],
        'Posłaniec' => [
            'ww' => 5,
            'us' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 5,
            'sw' => 5,
            'zyw' => 2,
        ],
        'Przemytnik' => [
            'ww' => 5,
            'us' => 5,
            'zr' => 10,
            'int' => 10,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Przepatrywacz' => [
            'ww' => 5,
            'us' => 10,
            'zr' => 10,
            'int' => 10,
            'sw' => 5,
            'zyw' => 2,
        ],
        'Przewoźnik' => [
            'ww' => 5,
            'us' => 5,
            'k' => 10,
            'odp' => 5,
            'zr' => 5,
            'int' => 5,
        ],
        'Rybak' => [
            'us' => 5,
            'k' => 10,
            'odp' => 5,
            'zr' => 10,
            'int' => 5,
            'zyw' => 2,
        ],
        'Rzecznik rodu' => [
            'ww' => 5,
            'us' => 5,
            'zr' => 5,
            'int' => 10,
            'sw' => 5,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Rzemieślnik' => [
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 5,
            'sw' => 10,
            'zyw' => 2,
        ],
        'Rzezimieszek' => [
            'ww' => 10,
            'k' => 10,
            'zr' => 10,
            'sw' => 10,
            'a' => 1,
            'zyw' => 2,
        ],
        'Skryba' => [
            'zr' => 10,
            'int' => 10,
            'sw' => 10,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Sługa' => [
            'ww' => 5,
            'k' => 5,
            'zr' => 10,
            'int' => 5,
            'sw' => 10,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Strażnik' => [
            'ww' => 10,
            'us' => 5,
            'k' => 5,
            'zr' => 5,
            'int' => 10,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Strażnik dróg' => [
            'ww' => 10,
            'us' => 10,
            'k' => 5,
            'zr' => 10,
            'int' => 5,
            'sw' => 5,
            'zyw' => 2,
        ],
        'Strażnik pól' => [
            'ww' => 5,
            'us' => 10,
            'k' => 5,
            'zr' => 10,
            'int' => 5,
            'sw' => 5,
            'zyw' => 2,
        ],
        'Strażnik więzienny' => [
            'ww' => 10,
            'k' => 10,
            'odp' => 10,
            'sw' => 5,
            'zyw' => 3,
        ],
        'Szczurołap' => [
            'ww' => 5,
            'us' => 10,
            'odp' => 5,
            'zr' => 10,
            'sw' => 10,
            'zyw' => 2,
        ],
        'Szermierz estalijski' => [
            'ww' => 15,
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 5,
            'a' => 1,
            'zyw' => 2,
        ],
        'Szlachcic' => [
            'ww' => 10,
            'us' => 5,
            'zr' => 5,
            'int' => 5,
            'sw' => 5,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Śmieciarz' => [
            'ww' => 5,
            'k' => 5,
            'odp' => 10,
            'zr' => 5,
            'sw' => 5,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Tarczownik' => [
            'ww' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'sw' => 5,
            'a' => 1,
            'zyw' => 2,
        ],
        'Uczeń czarodzieja' => [
            'zr' => 5,
            'int' => 10,
            'sw' => 15,
            'ogd' => 5,
            'zyw' => 2,
            'mag' => 1,
        ],
        'Węglarz' => [
            'ww' => 5,
            'k' => 5,
            'odp' => 5,
            'zr' => 5,
            'int' => 5,
            'sw' => 5,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Włóczykij' => [
            'ww' => 5,
            'us' => 10,
            'zr' => 10,
            'int' => 5,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Wojownik klanowy' => [
            'ww' => 5,
            'us' => 5,
            'zr' => 10,
            'int' => 10,
            'sw' => 5,
            'zyw' => 2,
        ],
        'Woźnica' => [
            'ww' => 5,
            'us' => 10,
            'zr' => 10,
            'sw' => 5,
            'ogd' => 5,
            'zyw' => 2,
        ],
        'Zabójca trolli' => [
            'ww' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 5,
            'sw' => 10,
            'a' => 1,
            'zyw' => 2,
        ],
        'Zarządca' => [
            'ww' => 5,
            'us' => 5,
            'k' => 5,
            'int' => 10,
            'sw' => 5,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Złodziej' => [
            'ww' => 5,
            'us' => 5,
            'zr' => 15,
            'int' => 5,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Żak' => [
            'zr' => 10,
            'int' => 10,
            'sw' => 5,
            'ogd' => 10,
            'zyw' => 2,
        ],
        'Żeglarz' => [
            'ww' => 10,
            'us' => 5,
            'k' => 10,
            'zr' => 10,
            'a' => 1,
            'zyw' => 2,
        ],
        'Żołnierz' => [
            'ww' => 10,
            'us' => 10,
            'zr' => 10,
            'sw' => 5,
            'a' => 5,
            'zyw' => 2,
        ],
        'Żołnierz okrętowy' => [
            'ww' => 10,
            'us' => 10,
            'k' => 10,
            'zr' => 5,
            'sw' => 5,
            'a' => 1,
            'zyw' => 3,
        ],
        'Arcykapłan' => [
            'ww' => 20,
            'us' => 20,
            'k' => 15,
            'odp' => 15,
            'zr' => 15,
            'int' => 20,
            'sw' => 30,
            'ogd' => 25,
            'a' => 1,
            'zyw' => 6,
            'mag' => 3,
        ],
        'Arcymag' => [
            'ww' => 15,
            'us' => 15,
            'k' => 5,
            'odp' => 15,
            'zr' => 20,
            'int' => 35,
            'sw' => 40,
            'ogd' => 20,
            'zyw' => 5,
            'mag' => 4,
        ],
        'Arystokrata' => [
            'ww' => 25,
            'us' => 15,
            'k' => 10,
            'odp' => 10,
            'zr' => 10,
            'int' => 20,
            'sw' => 20,
            'ogd' => 30,
            'a' => 1,
            'zyw' => 6,
        ],
        'Bard' => [
            'ww' => 10,
            'us' => 10,
            'zr' => 15,
            'int' => 10,
            'sw' => 5,
            'ogd' => 25,
            'zyw' => 4,
        ],
        'Biczownik' => [
            'ww' => 15,
            'k' => 10,
            'odp' => 15,
            'zr' => 5,
            'sw' => 20,
            'ogd' => 10,
            'a' => 1,
            'zyw' => 6,
        ],
        'Bosman' => [
            'ww' => 15,
            'us' => 15,
            'k' => 10,
            'odp' => 15,
            'zr' => 10,
            'int' => 10,
            'sw' => 10,
            'ogd' => 10,
            'a' => 1,
            'zyw' => 4,
        ],
        'Demagog' => [
            'ww' => 10,
            'us' => 10,
            'odp' => 10,
            'zr' => 15,
            'int' => 20,
            'sw' => 15,
            'ogd' => 30,
            'a' => 1,
            'zyw' => 4,
        ],
        'Dworzanin' => [
            'ww' => 5,
            'us' => 5,
            'zr' => 10,
            'int' => 20,
            'sw' => 20,
            'ogd' => 20,
            'zyw' => 4,
        ],
        'Fechtmistrz' => [
            'ww' => 40,
            'us' => 40,
            'k' => 25,
            'odp' => 25,
            'zr' => 30,
            'sw' => 20,
            'a' => 2,
            'zyw' => 8,
        ],
        'Herold' => [
            'ww' => 10,
            'us' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 15,
            'int' => 15,
            'sw' => 10,
            'ogd' => 20,
            'zyw' => 4,
        ],
        'Herszt banitów' => [
            'ww' => 20,
            'us' => 30,
            'k' => 10,
            'odp' => 20,
            'zr' => 10,
            'int' => 10,
            'sw' => 10,
            'ogd' => 20,
            'a' => 2,
            'zyw' => 6,
        ],
        'Inżynier' => [
            'ww' => 10,
            'us' => 15,
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 20,
            'sw' => 10,
            'zyw' => 4,
        ],
        'Kapitan' => [
            'ww' => 25,
            'us' => 20,
            'k' => 15,
            'odp' => 20,
            'zr' => 20,
            'int' => 20,
            'sw' => 25,
            'ogd' => 30,
            'a' => 2,
            'zyw' => 6,
        ],
        'Kapłan' => [
            'ww' => 10,
            'us' => 10,
            'k' => 5,
            'odp' => 10,
            'zr' => 5,
            'int' => 10,
            'sw' => 20,
            'ogd' => 15,
            'zyw' => 4,
            'mag' => 1,
        ],
        'Karczmarz' => [
            'ww' => 10,
            'us' => 5,
            'k' => 5,
            'odp' => 10,
            'zr' => 20,
            'int' => 10,
            'sw' => 10,
            'ogd' => 20,
            'zyw' => 4,
        ],
        'Książę złodziei' => [
            'ww' => 20,
            'us' => 20,
            'k' => 15,
            'odp' => 15,
            'zr' => 20,
            'int' => 25,
            'sw' => 20,
            'ogd' => 30,
            'a' => 2,
            'zyw' => 6,
        ],
        'Kupiec' => [
            'ww' => 10,
            'us' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 25,
            'sw' => 20,
            'ogd' => 20,
            'zyw' => 4,
        ],
        'Leśny duch' => [
            'ww' => 20,
            'us' => 30,
            'k' => 15,
            'odp' => 15,
            'zr' => 25,
            'int' => 20,
            'sw' => 20,
            'a' => 2,
            'zyw' => 6,
        ],
        'Łowca czarownic' => [
            'ww' => 30,
            'us' => 30,
            'k' => 15,
            'odp' => 15,
            'zr' => 15,
            'int' => 15,
            'sw' => 35,
            'ogd' => 20,
            'a' => 2,
            'zyw' => 6,
        ],
        'Łowca wampirów' => [
            'ww' => 20,
            'us' => 20,
            'k' => 10,
            'odp' => 20,
            'zr' => 15,
            'int' => 15,
            'sw' => 20,
            'a' => 1,
            'zyw' => 4,
        ],
        'Majordomus' => [
            'ww' => 10,
            'us' => 10,
            'k' => 10,
            'odp' => 10,
            'int' => 30,
            'sw' => 20,
            'ogd' => 25,
            'zyw' => 4,
        ],
        'Medyk' => [
            'k' => 10,
            'odp' => 10,
            'zr' => 15,
            'int' => 30,
            'sw' => 20,
            'ogd' => 15,
            'zyw' => 4,
        ],
        'Mistrz cieni' => [
            'ww' => 20,
            'us' => 20,
            'k' => 10,
            'odp' => 10,
            'zr' => 40,
            'int' => 25,
            'sw' => 20,
            'ogd' => 25,
            'a' => 1,
            'zyw' => 6,
        ],
        'Mistrz gildii' => [
            'ww' => 10,
            'us' => 10,
            'odp' => 10,
            'zr' => 15,
            'int' => 30,
            'sw' => 20,
            'ogd' => 35,
            'a' => 1,
            'zyw' => 5,
        ],
        'Mistrz magii' => [
            'ww' => 10,
            'us' => 10,
            'odp' => 10,
            'zr' => 15,
            'int' => 30,
            'sw' => 35,
            'ogd' => 15,
            'zyw' => 4,
            'mag' => 3,
        ],
        'Mistrz rzemiosła' => [
            'k' => 10,
            'odp' => 10,
            'zr' => 20,
            'int' => 10,
            'sw' => 10,
            'ogd' => 10,
            'zyw' => 3,
        ],
        'Mistrz zakonny' => [
            'ww' => 35,
            'us' => 10,
            'k' => 20,
            'odp' => 20,
            'zr' => 20,
            'int' => 15,
            'sw' => 25,
            'ogd' => 15,
            'a' => 2,
            'zyw' => 8,
        ],
        'Nawigator' => [
            'ww' => 10,
            'us' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 25,
            'sw' => 10,
            'ogd' => 5,
            'zyw' => 4,
        ],
        'Odkrywca' => [
            'ww' => 20,
            'us' => 20,
            'k' => 10,
            'odp' => 15,
            'zr' => 15,
            'int' => 25,
            'sw' => 20,
            'ogd' => 15,
            'a' => 1,
            'zyw' => 6,
        ],
        'Oficer' => [
            'ww' => 30,
            'us' => 20,
            'k' => 20,
            'odp' => 20,
            'zr' => 20,
            'int' => 15,
            'sw' => 15,
            'ogd' => 25,
            'a' => 2,
            'zyw' => 7,
        ],
        'Oprawca' => [
            'ww' => 15,
            'k' => 20,
            'odp' => 10,
            'zr' => 10,
            'int' => 10,
            'sw' => 20,
            'ogd' => 15,
            'zyw' => 4,
        ],
        'Paser' => [
            'ww' => 15,
            'us' => 10,
            'k' => 10,
            'odp' => 5,
            'zr' => 10,
            'int' => 5,
            'sw' => 10,
            'ogd' => 10,
            'a' => 1,
            'zyw' => 4,
        ],
        'Rajtar' => [
            'ww' => 20,
            'us' => 20,
            'k' => 10,
            'odp' => 10,
            'zr' => 15,
            'sw' => 15,
            'ogd' => 15,
            'a' => 1,
            'zyw' => 4,
        ],
        'Reketer' => [
            'ww' => 20,
            'us' => 15,
            'k' => 15,
            'odp' => 10,
            'zr' => 10,
            'sw' => 15,
            'ogd' => 10,
            'a' => 1,
            'zyw' => 5,
        ],
        'Rozbójnik' => [
            'ww' => 20,
            'us' => 20,
            'k' => 10,
            'odp' => 10,
            'zr' => 30,
            'int' => 20,
            'sw' => 15,
            'ogd' => 25,
            'a' => 1,
            'zyw' => 4,
        ],
        'Rycerz' => [
            'ww' => 25,
            'k' => 15,
            'odp' => 15,
            'zr' => 15,
            'int' => 5,
            'sw' => 15,
            'ogd' => 5,
            'a' => 1,
            'zyw' => 4,
        ],
        'Sierżant' => [
            'ww' => 20,
            'us' => 15,
            'k' => 10,
            'odp' => 10,
            'zr' => 10,
            'int' => 10,
            'sw' => 10,
            'ogd' => 20,
            'a' => 1,
            'zyw' => 4,
        ],
        'Skrytobójca' => [
            'ww' => 25,
            'us' => 25,
            'k' => 10,
            'odp' => 10,
            'zr' => 30,
            'int' => 20,
            'sw' => 10,
            'ogd' => 20,
            'a' => 2,
            'zyw' => 4,
        ],
        'Strzelec' => [
            'us' => 35,
            'k' => 10,
            'odp' => 10,
            'zr' => 25,
            'int' => 10,
            'sw' => 20,
            'ogd' => 15,
            'a' => 1,
            'zyw' => 4,
        ],
        'Szampierz' => [
            'ww' => 35,
            'k' => 15,
            'odp' => 15,
            'zr' => 20,
            'int' => 10,
            'sw' => 15,
            'a' => 2,
            'zyw' => 6,
        ],
        'Szarlatan' => [
            'ww' => 10,
            'us' => 10,
            'k' => 5,
            'odp' => 10,
            'zr' => 15,
            'int' => 15,
            'sw' => 15,
            'ogd' => 25,
            'zyw' => 4,
        ],
        'Szpieg' => [
            'ww' => 15,
            'us' => 15,
            'k' => 5,
            'odp' => 10,
            'zr' => 20,
            'int' => 20,
            'sw' => 35,
            'ogd' => 20,
            'a' => 1,
            'zyw' => 4,
        ],
        'Uczony' => [
            'ww' => 5,
            'us' => 5,
            'k' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 30,
            'sw' => 15,
            'ogd' => 15,
            'zyw' => 4,
        ],
        'Urzędnik' => [
            'ww' => 5,
            'us' => 5,
            'k' => 5,
            'odp' => 10,
            'int' => 20,
            'sw' => 10,
            'ogd' => 20,
            'zyw' => 4,
        ],
        'Weteran' => [
            'ww' => 20,
            'us' => 20,
            'k' => 10,
            'odp' => 10,
            'zr' => 15,
            'sw' => 15,
            'a' => 1,
            'zyw' => 6,
        ],
        'Wędrowny czarodziej' => [
            'ww' => 5,
            'us' => 5,
            'odp' => 5,
            'zr' => 10,
            'int' => 20,
            'sw' => 25,
            'ogd' => 10,
            'zyw' => 3,
            'mag' => 2,
        ],
        'Włamywacz' => [
            'ww' => 10,
            'us' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 25,
            'int' => 10,
            'sw' => 10,
            'zyw' => 4,
        ],
        'Wybraniec boży' => [
            'ww' => 15,
            'us' => 15,
            'k' => 10,
            'odp' => 10,
            'zr' => 10,
            'int' => 15,
            'sw' => 25,
            'ogd' => 20,
            'a' => 1,
            'zyw' => 5,
            'mag' => 2
        ],
        'Zabójca demonów' => [
            'ww' => 40,
            'k' => 30,
            'odp' => 30,
            'zr' => 20,
            'sw' => 30,
            'a' => 2,
            'zyw' => 8,
        ],
        'Zabójca olbrzymów' => [
            'ww' => 25,
            'k' => 15,
            'odp' => 15,
            'zr' => 10,
            'sw' => 20,
            'a' => 1,
            'zyw' => 6,
        ],
        'Zakonnik' => [
            'ww' => 10,
            'k' => 5,
            'odp' => 10,
            'int' => 15,
            'sw' => 15,
            'ogd' => 15,
            'zyw' => 4,
        ],
        'Zwadźca' => [
            'ww' => 20,
            'us' => 20,
            'k' => 10,
            'odp' => 20,
            'zr' => 20,
            'int' => 15,
            'sw' => 15,
            'ogd' => 10,
            'a' => 1,
            'zyw' => 4,
        ],
        'Zwiadowca' => [
            'ww' => 10,
            'us' => 10,
            'k' => 5,
            'odp' => 5,
            'zr' => 15,
            'int' => 15,
            'sw' => 10,
            'ogd' => 20,
            'a' => 2,
            'zyw' => 6,
        ],
    ];


    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $professions = Profession::all()->pluck('id', 'name')->toArray();
        $records = [];

        try {
            foreach ($this->professionsData as $professionName => $characteristics) {
                if (!isset($professions[$professionName])) {
                    continue;
                }

                foreach ($characteristics as $key => $advancement) {
                    $records[] = [
                        'profession_id' => $professions[$professionName],
                        'characteristic_id' => $this->characteristicMap[$key],
                        'available_advancement' => $advancement,
                    ];
                }
            }

            DB::beginTransaction();
            DB::table('profession_characteristics')->insert($records);
            DB::commit();
        } catch (\Throwable $exception) {
            try {
                DB::rollBack();
            } catch (\Throwable $e) {
                \Log::error('CRITICAL ERROR: rollback failed.');
                \Log::error($e);
            }
            \Log::error($exception);
        }
    }
}
